### ISSUE TITLE
request: How to register wasm mime on clojure ring server?

### ISSUE THREAD

**Issue by PlumpMath** [ring-clojure/ring#470] opened 2022-08-20 09:02 UTC
error: wasm streaming compile failed: TypeError: WebAssembly: Response has unsupported MIME type 'application/octet-stream' expected 'application/wasm'

How come there is no solution?

**Comment by PlumpMath** [comment] 2022-08-20 09:04
https://github.com/ring-clojure/ring/issues/450#issuecomment-1059063914

I want to register the compressed file as well.
If it can't be solved, boom... ha I'm so worried.

thanks.

**Comment by weavejester** [comment] 2022-08-20 11:09
Closing issue as duplicate of #450. Please don't open new issues just to ask a question.

**Closed by weavejester** 2022-08-20 11:09 UTC
